version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-shop
    restart: unless-stopped
    environment:
      PORT: 3000
      NODE_PATH: /src
      ENV: develpment
      DATABASE_TYPE: mysql
      DATABASE_DB: shop
      DATABASE_HOST: 10.6.0.5
      DATABASE_PORT: 3306
      DATABASE_USER: shop
      DATABASE_PASSWORD: shop
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.4
    volumes:
      - ./src:/app/src
    command: npm run start

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shop
    environment:
      MYSQL_ROOT_PASSWORD: shop
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
